services:
  matchmaking-service:
    image: matchmaking-service:latest
    build:
      context: ./MatchMaking.Service
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionString=redis:6379
    depends_on:
      - kafka
      - redis
      - zookeeper
    networks:
      - matchmaking-network

  matchmaking-worker1:
    image: matchmaking-worker:latest
    build:
      context: ./MatchMaking.Worker
      dockerfile: Dockerfile
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionString=redis:6379
      - MatchMaking__UsersPerMatch=3
    depends_on:
      - kafka
      - redis
      - zookeeper
    networks:
      - matchmaking-network

  matchmaking-worker2:
    image: matchmaking-worker:latest
    build:
      context: ./MatchMaking.Worker
      dockerfile: Dockerfile
    environment:
      - Kafka__BootstrapServers=kafka:9092
      - Redis__ConnectionString=redis:6379
      - MatchMaking__UsersPerMatch=3
    depends_on:
      - kafka
      - redis
      - zookeeper
    networks:
      - matchmaking-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - matchmaking-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - matchmaking-network

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - matchmaking-network

networks:
  matchmaking-network:
    driver: bridge